AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://idk-test-bucket-3009.s3.amazonaws.com/vpc.yaml

  SubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://idk-test-bucket-3009.s3.amazonaws.com/subnet.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId

  NatGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://idk-test-bucket-3009.s3.amazonaws.com/nat-gateway.yaml
      Parameters:
        PublicSubnetId: !GetAtt SubnetStack.Outputs.PublicSubnetId

  RouteTableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://idk-test-bucket-3009.s3.amazonaws.com/route-table.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt SubnetStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt SubnetStack.Outputs.PrivateSubnetId
        InternetGatewayId: !GetAtt VPCStack.Outputs.InternetGatewayId
        NatGatewayId: !GetAtt NatGatewayStack.Outputs.NatGatewayId

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://idk-test-bucket-3009.s3.amazonaws.com/ec2.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt SubnetStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt SubnetStack.Outputs.PrivateSubnetId
