AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PublicSubnetId:
    Type: String

Resources:
  EIPForNAT:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC

  MyNatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIPForNAT.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: idk-test-nat-gateway

Outputs:
  NatGatewayId:
    Value: !Ref MyNatGateway
